name: Pull from Lokalise

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v4.0.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 83752003642281bc7cd032.62890575 
          translations_path: |
            locales
          base_lang: en
          flat_naming: true
          file_format: json
